language : python
cache: pip

sudo: required

addons:
    chrome: stable

services:
  - docker

python:
  - "2.7"
  - "3.6"

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - pip install pycodestyle


install:
  - pip install -r requirements.txt
  - pip install -r webviz_components/dev-requirements.txt
  - pushd webviz_components
  - npm install
  - popd
  - virtualenv venv

script:
  - pushd webviz_components
  - npm run build:all
  - python setup.py install
  - npm run lint
  - npm run test
  - popd
  - pushd webviz_plotly
  - python setup.py install
  - pycodestyle src tests ../examples
  - pytest --doctest-modules src/webviz_plotly
  - pytest tests
  - popd
